# Path to the oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load.
# Config your puella in $WHAT_THE_ZSH/config/90-local.zsh/prompt.zsh
ZSH_THEME="puella"

# Enable hyphen-insensitive completion.
HYPHEN_INSENSITIVE="true"

# Choose which custom directory to use:
#ZSH_CUSTOM="$ZSH/custom"
#ZSH_CUSTOM="$HOME/.zsh-custom"

## Load plugins.
plugins=(
    git
    sudo
    systemd
    )

## Load oh-my-zsh
source $ZSH/oh-my-zsh.sh

## Load custom config
export WHAT_THE_ZSH=$ZSH_CUSTOM/what-the-zsh/
source $WHAT_THE_ZSH/scripts/load-config.zsh
